import { RequestHandler } from 'express';

export const SubjectPDF = {
    'ft_ssl_md5_try_rules': 'https://cdn.intra.42.fr/pdf/pdf/5945/ft_ssl_md5.en.pdf',
    'C Piscine C 00': 'https://cdn.intra.42.fr/pdf/pdf/36807/ko.subject.pdf',
    'C Piscine C 01': 'https://cdn.intra.42.fr/pdf/pdf/37200/ko.subject.pdf',
    'C Piscine C 02': 'https://cdn.intra.42.fr/pdf/pdf/37190/ko.subject.pdf',
    'C Piscine C 03': 'https://cdn.intra.42.fr/pdf/pdf/37277/ko.subject.pdf',
    'C Piscine C 04': 'https://cdn.intra.42.fr/pdf/pdf/37180/ko.subject.pdf',
    'C Piscine C 05': 'https://cdn.intra.42.fr/pdf/pdf/37170/ko.subject.pdf',
    'C Piscine C 06': 'https://cdn.intra.42.fr/pdf/pdf/37160/ko.subject.pdf',
    'C Piscine C 07': 'https://cdn.intra.42.fr/pdf/pdf/36497/ko.subject.pdf',
    'C Piscine C 08': 'https://cdn.intra.42.fr/pdf/pdf/37258/ko.subject.pdf',
    'C Piscine C 09': 'https://cdn.intra.42.fr/pdf/pdf/37248/ko.subject.pdf',
    'C Piscine C 12': 'https://cdn.intra.42.fr/pdf/pdf/37140/ko.subject.pdf',
    'C Piscine C 13': 'https://cdn.intra.42.fr/pdf/pdf/37132/ko.subject.pdf',
    'C Piscine Shell 00': 'https://cdn.intra.42.fr/pdf/pdf/37892/en.subject.pdf',
    'C Piscine Shell 01': 'https://cdn.intra.42.fr/pdf/pdf/37210/ko.subject.pdf',
    'ft_transcendence': 'https://cdn.intra.42.fr/pdf/pdf/35971/en.subject.pdf',
    '42run': 'https://cdn.intra.42.fr/pdf/pdf/30267/en.subject.pdf',
    '42SEOUL_TEST': 'https://cdn.intra.42.fr/pdf/pdf/23840/en.subject.pdf',
    'abstract-vm': 'https://cdn.intra.42.fr/pdf/pdf/30264/en.subject.pdf',
    'Apprentissage 2 ans - 1ère année': 'https://cdn.intra.42.fr/pdf/pdf/34790/en.subject.pdf',
    'Apprentissage 2 ans - 2ème année': 'https://cdn.intra.42.fr/pdf/pdf/28108/en.subject.pdf',
    'avaj-launcher': 'https://cdn.intra.42.fr/pdf/pdf/35448/en.subject.pdf',
    'Bgp At Doors of Autonomous Systems is Simple': 'https://cdn.intra.42.fr/pdf/pdf/37712/en.subject.pdf',
    'bomberman': 'https://cdn.intra.42.fr/pdf/pdf/35477/en.subject.pdf',
    'boot2root': 'https://cdn.intra.42.fr/pdf/pdf/37087/en.subject.pdf',
    'Born2beroot': 'https://cdn.intra.42.fr/pdf/pdf/35905/en.subject.pdf',
    'camagru': 'https://cdn.intra.42.fr/pdf/pdf/19609/en.subject.pdf',
    'Cinema': 'https://cdn.intra.42.fr/pdf/pdf/22234/en.subject.pdf',
    'cloud-1': 'https://cdn.intra.42.fr/pdf/pdf/30983/en.subject.pdf',
    'computorv1': 'https://cdn.intra.42.fr/pdf/pdf/30261/en.subject.pdf',
    'computorv2': 'https://cdn.intra.42.fr/pdf/pdf/30259/en.subject.pdf',
    'corewar': 'https://cdn.intra.42.fr/pdf/pdf/30254/en.subject.pdf',
    'CPP Module 00': 'https://cdn.intra.42.fr/pdf/pdf/35939/en.subject.pdf',
    'CPP Module 01': 'https://cdn.intra.42.fr/pdf/pdf/35942/en.subject.pdf',
    'CPP Module 02': 'https://cdn.intra.42.fr/pdf/pdf/35944/en.subject.pdf',
    'CPP Module 03': 'https://cdn.intra.42.fr/pdf/pdf/35947/en.subject.pdf',
    'CPP Module 04': 'https://cdn.intra.42.fr/pdf/pdf/35948/en.subject.pdf',
    'CPP Module 05': 'https://cdn.intra.42.fr/pdf/pdf/35949/en.subject.pdf',
    'CPP Module 06': 'https://cdn.intra.42.fr/pdf/pdf/35951/en.subject.pdf',
    'CPP Module 07': 'https://cdn.intra.42.fr/pdf/pdf/35954/en.subject.pdf',
    'CPP Module 08': 'https://cdn.intra.42.fr/pdf/pdf/35956/en.subject.pdf',
    'cub3d': 'https://cdn.intra.42.fr/pdf/pdf/35933/en.subject.pdf',
    'darkly': 'https://cdn.intra.42.fr/pdf/pdf/19003/en.subject.pdf',
    'death': 'https://cdn.intra.42.fr/pdf/pdf/13230/en.subject.pdf',
    'doom-nukem': 'https://cdn.intra.42.fr/pdf/pdf/26629/en.subject.pdf',
    'drivers-and-interrupts': 'https://cdn.intra.42.fr/pdf/pdf/34180/en.subject.pdf',
    'dr-quine': 'https://cdn.intra.42.fr/pdf/pdf/34050/en.subject.pdf',
    'dslr': 'https://cdn.intra.42.fr/pdf/pdf/19501/en.subject.pdf',
    'durex': 'https://cdn.intra.42.fr/pdf/pdf/13240/en.subject.pdf',
    'expert-system': 'https://cdn.intra.42.fr/pdf/pdf/30251/en.subject.pdf',
    'famine': 'https://cdn.intra.42.fr/pdf/pdf/13234/en.subject.pdf',
    'FdF': 'https://cdn.intra.42.fr/pdf/pdf/35925/en.subject.pdf',
    'filesystem': 'https://cdn.intra.42.fr/pdf/pdf/13280/en.subject.pdf',
    'fix-me': 'https://cdn.intra.42.fr/pdf/pdf/35450/en.subject.pdf',
    'fract-ol': 'https://cdn.intra.42.fr/pdf/pdf/35928/en.subject.pdf',
    'freddie-mercury': 'https://cdn.intra.42.fr/pdf/pdf/29620/en.subject.pdf',
    'ft_ality': 'https://cdn.intra.42.fr/pdf/pdf/30250/en.subject.pdf',
    'ft_containers': 'https://cdn.intra.42.fr/pdf/pdf/35960/en.subject.pdf',
    'ft_hangouts': 'https://cdn.intra.42.fr/pdf/pdf/13208/en.subject.pdf',
    'ft_irc': 'https://cdn.intra.42.fr/pdf/pdf/35966/en.subject.pdf',
    'ft_linear_regression': 'https://cdn.intra.42.fr/pdf/pdf/30248/en.subject.pdf',
    'ft_linux': 'https://cdn.intra.42.fr/pdf/pdf/35492/en.subject.pdf',
    'ft_ls': 'https://cdn.intra.42.fr/pdf/pdf/30246/en.subject.pdf',
    'ft_malcolm': 'https://cdn.intra.42.fr/pdf/pdf/15289/en.subject.pdf',
    'ft_newton': 'https://cdn.intra.42.fr/pdf/pdf/22536/en.subject.pdf',
    'ft_nmap': 'https://cdn.intra.42.fr/pdf/pdf/20631/en.subject.pdf',
    'ft_ping': 'https://cdn.intra.42.fr/pdf/pdf/30244/en.subject.pdf',
    'ft_printf': 'https://cdn.intra.42.fr/pdf/pdf/35908/en.subject.pdf',
    'ft_script': 'https://cdn.intra.42.fr/pdf/pdf/30242/en.subject.pdf',
    'ft_select': 'https://cdn.intra.42.fr/pdf/pdf/30988/en.subject.pdf',
    'ft_server': 'https://cdn.intra.42.fr/pdf/pdf/34219/en.subject.pdf',
    'ft_services': 'https://cdn.intra.42.fr/pdf/pdf/36177/en.subject.pdf',
    'ft_ssl_des': 'https://cdn.intra.42.fr/pdf/pdf/19604/en.subject.pdf',
    'ft_ssl_md5': 'https://cdn.intra.42.fr/pdf/pdf/30241/en.subject.pdf',
    'ft_ssl_rsa': 'https://cdn.intra.42.fr/pdf/pdf/19602/en.subject.pdf',
    'ft_traceroute': 'https://cdn.intra.42.fr/pdf/pdf/13249/en.subject.pdf',
    'ft_turing': 'https://cdn.intra.42.fr/pdf/pdf/30240/en.subject.pdf',
    'ft_vox': 'https://cdn.intra.42.fr/pdf/pdf/15953/en.subject.pdf',
    'FWA': 'https://cdn.intra.42.fr/pdf/pdf/22233/en.subject.pdf',
    'gbmu': 'https://cdn.intra.42.fr/pdf/pdf/30238/en.subject.pdf',
    'get_next_line': 'https://cdn.intra.42.fr/pdf/pdf/35912/en.subject.pdf',
    'gomoku': 'https://cdn.intra.42.fr/pdf/pdf/36162/en.subject.pdf',
    'guimp': 'https://cdn.intra.42.fr/pdf/pdf/30235/en.subject.pdf',
    'h42n42': 'https://cdn.intra.42.fr/pdf/pdf/30233/en.subject.pdf',
    'humangl': 'https://cdn.intra.42.fr/pdf/pdf/31352/en.subject.pdf',
    'hypertube': 'https://cdn.intra.42.fr/pdf/pdf/31355/en.subject.pdf',
    'Inception': 'https://cdn.intra.42.fr/pdf/pdf/35968/en.subject.pdf',
    'Inception-of-Things': 'https://cdn.intra.42.fr/pdf/pdf/36158/en.subject.pdf',
    'Internship I': 'https://cdn.intra.42.fr/pdf/pdf/15391/en.subject.pdf',
    'Internship II': 'https://cdn.intra.42.fr/pdf/pdf/15393/en.subject.pdf',
    'in-the-shadows': 'https://cdn.intra.42.fr/pdf/pdf/15973/en.subject.pdf',
    'kfs-1': 'https://cdn.intra.42.fr/pdf/pdf/38037/en.subject.pdf',
    'kfs-2': 'https://cdn.intra.42.fr/pdf/pdf/13287/en.subject.pdf',
    'kfs-3': 'https://cdn.intra.42.fr/pdf/pdf/13288/en.subject.pdf',
    'kfs-4': 'https://cdn.intra.42.fr/pdf/pdf/13289/en.subject.pdf',
    'kfs-5': 'https://cdn.intra.42.fr/pdf/pdf/13290/en.subject.pdf',
    'kfs-6': 'https://cdn.intra.42.fr/pdf/pdf/13291/en.subject.pdf',
    'kfs-7': 'https://cdn.intra.42.fr/pdf/pdf/9398/en.subject.pdf',
    'kfs-8': 'https://cdn.intra.42.fr/pdf/pdf/13292/en.subject.pdf',
    'kfs-9': 'https://cdn.intra.42.fr/pdf/pdf/13293/en.subject.pdf',
    'kfs-x': 'https://cdn.intra.42.fr/pdf/pdf/21136/en.subject.pdf',
    'krpsim': 'https://cdn.intra.42.fr/pdf/pdf/13362/en.subject.pdf',
    'lem_in': 'https://cdn.intra.42.fr/pdf/pdf/30231/en.subject.pdf',
    'lem-ipc': 'https://cdn.intra.42.fr/pdf/pdf/30229/en.subject.pdf',
    'libasm': 'https://cdn.intra.42.fr/pdf/pdf/36173/en.subject.pdf',
    'Libft': 'https://cdn.intra.42.fr/pdf/pdf/35902/en.subject.pdf',
    'little-penguin-1': 'https://cdn.intra.42.fr/pdf/pdf/35451/en.subject.pdf',
    'malloc': 'https://cdn.intra.42.fr/pdf/pdf/33934/en.subject.pdf',
    'matcha': 'https://cdn.intra.42.fr/pdf/pdf/17245/en.subject.pdf',
    'matt-daemon': 'https://cdn.intra.42.fr/pdf/pdf/13309/en.subject.pdf',
    'MessageQueue': 'https://cdn.intra.42.fr/pdf/pdf/22238/en.subject.pdf',
    'MicroServices': 'https://cdn.intra.42.fr/pdf/pdf/22237/en.subject.pdf',
    'miniRT': 'https://cdn.intra.42.fr/pdf/pdf/35936/en.subject.pdf',
    'minishell': 'https://cdn.intra.42.fr/pdf/pdf/26270/en.subject.pdf',
    'minitalk': 'https://cdn.intra.42.fr/pdf/pdf/35917/en.subject.pdf',
    'mod1': 'https://cdn.intra.42.fr/pdf/pdf/30227/en.subject.pdf',
    'multilayer-perceptron': 'https://cdn.intra.42.fr/pdf/pdf/30225/en.subject.pdf',
    'music-room': 'https://cdn.intra.42.fr/pdf/pdf/30223/en.subject.pdf',
    'NetPractice': 'https://cdn.intra.42.fr/pdf/pdf/35957/en.subject.pdf',
    'nibbler': 'https://cdn.intra.42.fr/pdf/pdf/30220/en.subject.pdf',
    'nm': 'https://cdn.intra.42.fr/pdf/pdf/33930/en.subject.pdf',
    'n-puzzle': 'https://cdn.intra.42.fr/pdf/pdf/30222/en.subject.pdf',
    'Old-CPP Module 00': 'https://cdn.intra.42.fr/pdf/pdf/26479/en.subject.pdf',
    'Old-CPP Module 01': 'https://cdn.intra.42.fr/pdf/pdf/26481/en.subject.pdf',
    'Old-CPP Module 02': 'https://cdn.intra.42.fr/pdf/pdf/26482/en.subject.pdf',
    'Old-CPP Module 03': 'https://cdn.intra.42.fr/pdf/pdf/26484/en.subject.pdf',
    'Old-CPP Module 04': 'https://cdn.intra.42.fr/pdf/pdf/24746/en.subject.pdf',
    'Old-CPP Module 05': 'https://cdn.intra.42.fr/pdf/pdf/27715/en.subject.pdf',
    'Old-CPP Module 06': 'https://cdn.intra.42.fr/pdf/pdf/26488/en.subject.pdf',
    'Old-CPP Module 07': 'https://cdn.intra.42.fr/pdf/pdf/26491/en.subject.pdf',
    'Old-CPP Module 08': 'https://cdn.intra.42.fr/pdf/pdf/26493/en.subject.pdf',
    'Old-IRC': 'https://cdn.intra.42.fr/pdf/pdf/24329/en.subject.pdf',
    'Old-Philosophers': 'https://cdn.intra.42.fr/pdf/pdf/35366/en.subject.pdf',
    'Open Project': 'https://cdn.intra.42.fr/pdf/pdf/13354/en.subject.pdf',
    'override': 'https://cdn.intra.42.fr/pdf/pdf/37091/en.subject.pdf',
    'particle-system': 'https://cdn.intra.42.fr/pdf/pdf/30216/en.subject.pdf',
    'Part_Time I': 'https://cdn.intra.42.fr/pdf/pdf/33901/en.subject.pdf',
    'Part_Time II': 'https://cdn.intra.42.fr/pdf/pdf/33903/en.subject.pdf',
    'pestilence': 'https://cdn.intra.42.fr/pdf/pdf/13236/en.subject.pdf',
    'Philosophers': 'https://cdn.intra.42.fr/pdf/pdf/35931/en.subject.pdf',
    'pipex': 'https://cdn.intra.42.fr/pdf/pdf/35920/en.subject.pdf',
    'Piscine Java': 'https://cdn.intra.42.fr/pdf/pdf/22226/en.subject.pdf',
    'process-and-memory': 'https://cdn.intra.42.fr/pdf/pdf/32888/en.subject.pdf',
    'push_swap': 'https://cdn.intra.42.fr/pdf/pdf/35914/en.subject.pdf',
    'rainfall': 'https://cdn.intra.42.fr/pdf/pdf/37089/en.subject.pdf',
    'red-tetris': 'https://cdn.intra.42.fr/pdf/pdf/29965/en.subject.pdf',
    'Restful': 'https://cdn.intra.42.fr/pdf/pdf/22236/en.subject.pdf',
    'rubik': 'https://cdn.intra.42.fr/pdf/pdf/30212/en.subject.pdf',
    'scop': 'https://cdn.intra.42.fr/pdf/pdf/35866/en.subject.pdf',
    'shaderpixel': 'https://cdn.intra.42.fr/pdf/pdf/15958/en.subject.pdf',
    'snow-crash': 'https://cdn.intra.42.fr/pdf/pdf/19197/en.subject.pdf',
    'so_long': 'https://cdn.intra.42.fr/pdf/pdf/35923/en.subject.pdf',
    'SpringBoot': 'https://cdn.intra.42.fr/pdf/pdf/22235/en.subject.pdf',
    'Startup Internship': 'https://cdn.intra.42.fr/pdf/pdf/30722/en.subject.pdf',
    'strace': 'https://cdn.intra.42.fr/pdf/pdf/32858/en.subject.pdf',
    'swifty-companion': 'https://cdn.intra.42.fr/pdf/pdf/23559/en.subject.pdf',
    'swifty-proteins': 'https://cdn.intra.42.fr/pdf/pdf/23566/en.subject.pdf',
    'swingy': 'https://cdn.intra.42.fr/pdf/pdf/35449/en.subject.pdf',
    'taskmaster': 'https://cdn.intra.42.fr/pdf/pdf/30205/en.subject.pdf',
    'total-perspective-vortex': 'https://cdn.intra.42.fr/pdf/pdf/30208/en.subject.pdf',
    'userspace_digressions': 'https://cdn.intra.42.fr/pdf/pdf/30207/en.subject.pdf',
    'war': 'https://cdn.intra.42.fr/pdf/pdf/13232/en.subject.pdf',
    'webserv': 'https://cdn.intra.42.fr/pdf/pdf/35963/en.subject.pdf',
    'woody-woodpacker': 'https://cdn.intra.42.fr/pdf/pdf/33532/en.subject.pdf',
    'xv': 'https://cdn.intra.42.fr/pdf/pdf/31354/en.subject.pdf',
    'zappy': 'https://cdn.intra.42.fr/pdf/pdf/13257/en.subject.pdf'
};

const getSubjectPDF: RequestHandler = async (req, res) => {
    try {
        const subject = req.params.subject;
        const subjectPDFLink = SubjectPDF[subject];

        if (subjectPDFLink === undefined) throw new Error('Invalid Subject');
        res.status(200).json({
            success: true,
            subjectPDF: subjectPDFLink,
        });
    } catch (error) {
        res.status(400).json({
            success: false,
            error: {
                code: error.name,
                message: error.message,
            },
        });
    }
};

export default getSubjectPDF;
