name: server-CD
on:
  pull_request:
    branches: development

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm build
      
      - name: Clean
        run: npm run clean

      - name: zip 생성
        run: zip -qq -r ./server-sorce.zip .
        shell: bash

      - name: S3 업로드
        run: aws deploy push --application-name server-cd --description "Matching42-server" --s3-location s3://matching42-server-cd/server-sorce.zip --source .

      - name: Code Deploy
        run: aws deploy create-deployment --application-name server-cd --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name Matching42-server-cd --s3-location bucket=matching42-server-cd,bundleType=zip,key=./server-sorce.zip
